// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Yqtw6YGK5CC4AgSG598HNToWRQRrs1I',
    appId: '1:499503220653:android:8fbc3691a2ba7d394ac324',
    messagingSenderId: '499503220653',
    projectId: 'guessthemovie-dcb6b',
    databaseURL: 'https://guessthemovie-dcb6b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guessthemovie-dcb6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7L50Qu3cVwNPdj9dRDKpXgQyDJTUcWMg',
    appId: '1:499503220653:ios:a9d4f7dceb764a274ac324',
    messagingSenderId: '499503220653',
    projectId: 'guessthemovie-dcb6b',
    databaseURL: 'https://guessthemovie-dcb6b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'guessthemovie-dcb6b.firebasestorage.app',
    iosBundleId: 'com.edkagames.guessthemovie',
  );
}
